// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl6cu6vGmNofqcTo_xkr9JypCWsa2acjE',
    appId: '1:112280073389:web:884f37a5a44472ae990224',
    messagingSenderId: '112280073389',
    projectId: 'examtask-9c963',
    authDomain: 'examtask-9c963.firebaseapp.com',
    storageBucket: 'examtask-9c963.appspot.com',
    measurementId: 'G-SGF6LGL6EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbVQILu54FA6lvA71U_H6JK3x-0TkVddg',
    appId: '1:112280073389:android:919dc5426da092d7990224',
    messagingSenderId: '112280073389',
    projectId: 'examtask-9c963',
    storageBucket: 'examtask-9c963.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Uu0CJhgnqZBegaY08lJML4fyw7LXueU',
    appId: '1:112280073389:ios:fd5efc329c3eca72990224',
    messagingSenderId: '112280073389',
    projectId: 'examtask-9c963',
    storageBucket: 'examtask-9c963.appspot.com',
    iosBundleId: 'com.example.examtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1Uu0CJhgnqZBegaY08lJML4fyw7LXueU',
    appId: '1:112280073389:ios:fd5efc329c3eca72990224',
    messagingSenderId: '112280073389',
    projectId: 'examtask-9c963',
    storageBucket: 'examtask-9c963.appspot.com',
    iosBundleId: 'com.example.examtask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl6cu6vGmNofqcTo_xkr9JypCWsa2acjE',
    appId: '1:112280073389:web:e56d230ce20d19a4990224',
    messagingSenderId: '112280073389',
    projectId: 'examtask-9c963',
    authDomain: 'examtask-9c963.firebaseapp.com',
    storageBucket: 'examtask-9c963.appspot.com',
    measurementId: 'G-D2Z4VEXBFR',
  );
}
